CREATE DEFINER=`root`@`localhost` PROCEDURE `RATING FOR TYPE OF SERVICE`()
BEGIN
SELECT SUP.SUPP_ID, SUP.SUPP_NAME, R.RAT_RATSTARS,
CASE
WHEN R.RAT_RATSTARS =5 THEN 'Excellent Service'
WHEN R.RAT_RATSTARS >=4 THEN 'Good Service'
WHEN R.RAT_RATSTARS >2 THEN 'Average service'
ELSE 'POOR SERVICE'
END AS TYPE_OF_SERVICE
FROM RATING R, SUPPLIER SUP, `ORDER` ORD,SUPPLIER_PRICING SUPP
WHERE R.ORD_ID =ORD.ORD_ID
AND ORD.PRICING_ID = SUPP.PRICING_ID
AND SUPP.SUPP_ID = SUP.SUPP_ID; 
END